/// The transaction as the rest of the app sees it — KHA-25, US-B1,
/// AC-B1.1–AC-B1.4, NFR-A1.
///
/// ## Why there is a value type here as well as a database row
///
/// `TransactionRow` (generated by Drift) is a *storage* shape: money arrives
/// as three loose columns, the instrument as an id, provenance as two strings.
/// Every screen that consumed it would have to re-assemble those, and the
/// first one to forget the currency column would render an amount without one.
/// [LedgerTransaction] assembles them once: money is [Money], the instrument
/// is an object, provenance is a small closed type.
///
/// ## Null means "the message did not say" — everywhere, without exception
///
/// AC-B1.3 requires an absent field to be **explicitly unknown, never blank,
/// zero, or guessed**, and KHA-25 sharpens it: *"'Unknown' must be
/// distinguishable from 'zero' in the data model, not just in the UI — a
/// zero-amount transaction and an unparsed-amount transaction are different
/// facts."*
///
/// So no field here has a default. [feeAmount] is `null` when the message
/// mentioned no fee and `Money(0)` only if a bank genuinely printed a zero
/// fee. The UI renders the first as *"Not stated in message"* and the second
/// as *"0.00 SAR"*, because those are different statements about the world.
///
/// ## AC-B1.4 — exact precision, no rounding
///
/// [amount] is a [Money], which wraps an arbitrary-precision decimal and
/// round-trips through storage as its canonical string (ADR-002). A value
/// parsed as `45.90` is stored as `"45.90"` and read back as `45.90` — never
/// via a floating-point step that could turn it into `45.899999`. There is no
/// code path in this app that converts an amount to a float, because [Money]
/// exposes no method to do so.
library;

import '../../core/money/money.dart';
import '../../core/money/sign_convention.dart';

/// Where a transaction came from — NFR-A1's three sources.
///
/// Kept as string constants (not a Dart `enum`) because these exact spellings
/// are what the `provenance` column stores; one vocabulary, one place.
abstract final class TransactionProvenance {
  /// Derived from an SMS by the parser. Carries a source-message reference.
  static const String sms = 'sms';

  /// Entered by the user with no message behind it (US-B4, cash spending).
  static const String manual = 'manual';

  /// Created by statement reconciliation (Epic H). Not built yet — the value
  /// exists now because NFR-A1 requires provenance to be recorded from the
  /// first write, and retrofitting a fourth source later is exactly what
  /// build-plan §5 warns against ("P7 must not create a fourth, untracked
  /// path").
  static const String statement = 'statement';
}

/// A refinement of [TransactionProvenance], not a fourth value of it.
abstract final class ProvenanceDetail {
  /// KHA-64 / AC-A4.2: an SMS the parser could not read, completed by the
  /// user from the review queue. Provenance stays [TransactionProvenance.sms]
  /// because the source message is real and still referenced; this records
  /// that the *values* were supplied by a person.
  static const String manualCompletion = 'manual_completion';
}

/// The instrument a transaction hit, as much of it as is known.
final class LedgerInstrument {
  final int id;
  final int bankId;

  /// `account` | `card` — see `instrument_identity.dart`.
  final String kind;

  /// Always present and always masked (NFR-S2), e.g. `****4821`.
  final String maskedIdentifier;

  /// Null until the user renames it, at which point it becomes the label and
  /// the masked identifier becomes the subtitle (AC-B3.1, AC-B15.2).
  final String? friendlyName;

  final String? network;
  final String? cardType;

  /// AC-B14.2/B14.3 — the settlement account, or null for "not linked".
  /// Null is displayed as unlinked and is **never** inferred.
  final int? settlementAccountId;

  const LedgerInstrument({
    required this.id,
    required this.bankId,
    required this.kind,
    required this.maskedIdentifier,
    this.friendlyName,
    this.network,
    this.cardType,
    this.settlementAccountId,
  });

  /// Ids and a kind only — no identifier digits (NFR-S4).
  @override
  String toString() => 'LedgerInstrument(#$id, $kind)';
}

/// One transaction, assembled.
final class LedgerTransaction {
  final int id;

  /// The native amount, in the currency the message stated (NFR-A5).
  final Money amount;

  /// `debit` | `credit`. Sign lives here, never in [amount] — a negative
  /// `Money` would break every invariant that assumes amounts are magnitudes
  /// (see `transaction_table.dart`).
  final String direction;

  /// The matched rule's `messageType`, e.g. `pos_purchase`, `card_repayment`.
  final String transactionType;

  /// Whether this counts toward "money spent" (US-B10/B11). `false` for
  /// internal transfers, income, and card repayment — repayment settles spend
  /// already counted, and counting it twice makes every total wrong.
  final bool affectsSpend;

  /// When the movement happened (UTC), or null if nothing dated it.
  final DateTime? occurredAt;

  /// `sms_explicit` | `sms_local_assumed` | `received_at_fallback`.
  final String? timeSource;

  final String? merchantRawText;
  final String? counterpartyName;
  final String? counterpartyBankName;
  final String? referenceNumber;

  // --- P4a: the categorization block (KHA-30, KHA-31) -----------------------

  /// The stored `category_id`. **Null means uncategorized** — one stored
  /// representation, resolved to the explicit *Uncategorized* category at
  /// display time by `CategoryResolver`, which is what makes AC-C1.1's "never
  /// a blank" true (see `transaction_table.dart`).
  final String? categoryId;

  /// `user` | `rule` | `default` | `none`, or null for a row written before
  /// any categorization decision existed. AC-D2.2's "was this automatic?".
  final String? categorySource;

  /// `0.0`–`1.0`, or null when nothing has judged this row. Not money, so a
  /// double is correct here (architecture §4.2).
  final double? categoryConfidence;

  /// `merchant_rule.id` of the rule that produced [categoryId] — AC-D2.2's
  /// "and ideally why".
  final int? categoryRuleId;

  /// The resolved merchant, or null when the message named none.
  final int? merchantId;

  /// The bank's own inline conversion, where the message printed one
  /// (ADR-009 prefers it over anything derived).
  final Money? convertedAmount;

  /// The FX / international fee as its **own** component — never folded into
  /// [amount] (PRD §3.4).
  final Money? feeAmount;

  /// Exact decimal string. A rate is not an amount of money, so it is not a
  /// [Money]; it is emphatically not a float either (ADR-002).
  final String? fxRate;

  /// The date [fxRate] applies to — **KHA-70 / AC-B9.3**.
  ///
  /// Null means the source stated no date, which the detail screen renders as
  /// the words *"date unknown"*. It is never defaulted to the transaction
  /// date at *display* time; where the parser can legitimately infer it from
  /// the message it writes it at *ingestion* time and says so through
  /// [fxRateSource]. Inferring silently in the UI would make an undated rate
  /// look authoritative, which was the whole of defect D-QA-2.
  final DateTime? fxRateDate;

  /// `sms_implied` | `sms_stated` | `user` | `carried_forward` — see
  /// `base_currency.dart`'s `FxRateSource`. Null when no rate is recorded.
  final String? fxRateSource;

  /// **ADR-009 case 4.** True when this transaction is in a foreign currency
  /// and the message supplied neither a converted amount nor a rate, so no
  /// base-currency figure can be produced without inventing one.
  ///
  /// Such a transaction is **excluded from base-currency totals** and counted
  /// on an explicit "N transactions not converted" line, so a period figure is
  /// visibly incomplete rather than silently wrong.
  final bool conversionPending;

  /// The internal-transfer pair this transaction belongs to, when a link has
  /// been persisted (architecture §4.2 `InternalTransferLink.groupId`). Null
  /// for everything else, including pairs that are only *derived* at read
  /// time — see `internal_transfer.dart`.
  final String? internalTransferGroupId;

  /// `internal` | `candidate` | `external`, when a decision has been
  /// persisted. Null means "nobody has ruled on this", and the detector
  /// derives a state at read time instead. A persisted value always wins,
  /// because it is a decision a **person** made (AC-B11.2).
  final String? internalTransferState;

  /// Balance reported after the movement, where a message stated one.
  /// Informational; never summed, never treated as spend.
  final Money? remainingBalance;

  final LedgerInstrument? instrument;

  /// What the message said about the instrument, even when it resolved to
  /// none (too few digits to key on). Keeping it means the detail view can
  /// still show the user what the bank printed instead of a bare "unknown".
  final String? instrumentMaskedRefFromMessage;

  final String provenance;
  final String? provenanceDetail;

  /// `raw_message.id` — AC-B1.2's link to the original text.
  final int? sourceMessageId;

  final String? rulePackId;
  final String? rulePackVersion;
  final String? ruleId;

  final bool needsReview;
  final String? reviewReason;
  final int? possibleDuplicateOfId;

  final bool isDeleted;
  final DateTime? deletedAt;

  const LedgerTransaction({
    required this.id,
    required this.amount,
    required this.direction,
    required this.transactionType,
    required this.affectsSpend,
    this.occurredAt,
    this.timeSource,
    this.merchantRawText,
    this.counterpartyName,
    this.counterpartyBankName,
    this.referenceNumber,
    this.categoryId,
    this.categorySource,
    this.categoryConfidence,
    this.categoryRuleId,
    this.merchantId,
    this.convertedAmount,
    this.feeAmount,
    this.fxRate,
    this.fxRateDate,
    this.fxRateSource,
    this.conversionPending = false,
    this.internalTransferGroupId,
    this.internalTransferState,
    this.remainingBalance,
    this.instrument,
    this.instrumentMaskedRefFromMessage,
    this.provenance = TransactionProvenance.sms,
    this.provenanceDetail,
    this.sourceMessageId,
    this.rulePackId,
    this.rulePackVersion,
    this.ruleId,
    this.needsReview = false,
    this.reviewReason,
    this.possibleDuplicateOfId,
    this.isDeleted = false,
    this.deletedAt,
  });

  /// True for a credit (refund, income, incoming transfer). A credit
  /// **reduces** period spend rather than increasing it (US-B7).
  ///
  /// The sign of a movement lives here and in [direction] alone — the stored
  /// [amount] is always a non-negative magnitude. That is the app's settled
  /// sign convention; `sign_convention.dart` states it in full, including why
  /// the alternatives were rejected and what it obliges a manual-entry form
  /// to do.
  bool get isCredit => direction == MovementDirection.credit;

  /// True when a person supplied the values, whether from scratch (US-B4) or
  /// by completing an unparsed message (AC-A4.2). Drives the "Manual" badge
  /// AC-B4.3 requires.
  bool get isUserEntered =>
      provenance == TransactionProvenance.manual ||
      provenanceDetail == ProvenanceDetail.manualCompletion;

  /// **No amount, no merchant, no identifier** (NFR-S4, ADR-015). This type
  /// carries essentially everything sensitive in the app, which makes an
  /// accidental `'$transaction'` in a log line the most plausible leak there
  /// is.
  @override
  String toString() => 'LedgerTransaction(#$id, $transactionType)';
}
